spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: azure
    password: azure1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false